std_msgs/Header header
float64 dt
uint32 horizon
uint32 manip_dof
float64[] base_traj_xyyaw
float64[] arm_start_q
float64[] arm_goal_q
float64[] arm_seed_q
bool use_guidance
float64 w_smooth
float64 w_joint_limit
float64 timeout_ms
---
bool success
string status
float64 score
float64 infer_ms
float64[] arm_traj_q

